"use strict";
const {
  Model
} = require("sequelize");

const { v4: uuid } = require('uuid');

module.exports = (sequelize, DataTypes) => {
  class IL_DualCredit_Entity extends Model {
    /**
     * Helper method for defining associations.
     * This method is not a part of Sequelize lifecycle.
     * The `models/index` file will call this method automatically.
     */
    static associate(models) {
        
    }
  }
  IL_DualCredit_Entity.init({
    RCDTS: DataTypes.STRING(500),
    Type: DataTypes.STRING(500),
    School_Name: DataTypes.STRING(500),
    District: DataTypes.STRING(500),
    City: DataTypes.STRING(500),
    County: DataTypes.STRING(500),
    School_Type: DataTypes.STRING(500),
    State_Senate_District: DataTypes.STRING(500),
    State_Representative_District: DataTypes.STRING(500),
    N_Student_Enrollment: DataTypes.BIGINT,
    P_Student_Enrollment_White: DataTypes.DECIMAL(3,2),
    N_White: DataTypes.BIGINT,
    P_Student_Enrollment_B_or_AA: DataTypes.DECIMAL(3,2),
    N_Black: DataTypes.BIGINT,
    P_Student_Enrollment_H_or_L: DataTypes.DECIMAL(3,2),
    N_Latino: DataTypes.BIGINT,
    P_Student_Enrollment_Asian: DataTypes.DECIMAL(3,2),
    N_Asian: DataTypes.BIGINT,
    P_Student_Enrollment_NH_or_Other_PI: DataTypes.DECIMAL(3,2),
    N_Native: DataTypes.BIGINT,
    P_Student_Enrollment_AI_or_AN: DataTypes.DECIMAL(3,2),
    N_American_Indian: DataTypes.BIGINT,
    P_Student_Enrollment_Two_or_More_Races: DataTypes.DECIMAL(3,2),
    N_Two_or_More: DataTypes.BIGINT,
    P_Student_Enrollment_Children_with_Disabilities: DataTypes.DECIMAL(3,2),
    N_Disabilities: DataTypes.BIGINT,
    P_Student_Enrollment_EL: DataTypes.DECIMAL(3,2),
    N_EL: DataTypes.BIGINT,
    P_Student_Enrollment_IEP: DataTypes.DECIMAL(3,2),
    N_IEP: DataTypes.BIGINT,
    P_Student_Enrollment_Low_Income: DataTypes.DECIMAL(3,2),
    N_LI: DataTypes.BIGINT,
    P_Student_Enrollment_Homeless: DataTypes.DECIMAL(3,2),
    N_Homeless: DataTypes.BIGINT,
    P_Postsecondary_Institution_within_12_months: DataTypes.DECIMAL(3,2),
    P_Community_College_Remediation: DataTypes.DECIMAL(3,2),
    N_Students_who_took_Dual_Credit_classes_912_Total: DataTypes.BIGINT,
    N_Dual_Credit_Students_White: DataTypes.BIGINT,
    P_DC: DataTypes.DECIMAL(3,2),
    P_TOTAL_White: DataTypes.DECIMAL(3,2),
    N_Dual_Credit_Students_B_or_AA: DataTypes.BIGINT,
    N_Dual_Credit_Students_H_or_L: DataTypes.BIGINT,
    N_Dual_Credit_Students_Asian: DataTypes.BIGINT,
    N_Dual_Credit_Students_NH_or_Other_PI: DataTypes.BIGINT,
    N_Dual_Credit_Students_AI_or_AN: DataTypes.BIGINT,
    N_Dual_Credit_Students_Two_or_More_Races: DataTypes.BIGINT,
    N_Dual_Credit_Students_Children_with_Disabilities: DataTypes.BIGINT,
    N_Dual_Credit_Students_EL: DataTypes.BIGINT,
    N_Dual_Credit_Students_NonEL: DataTypes.BIGINT,
    N_Dual_Credit_Students_IEP: DataTypes.BIGINT,
    N_Dual_Credit_Students_NonIEP: DataTypes.BIGINT,
    N_Dual_Credit_Students_Low_Income: DataTypes.BIGINT,
    N_Dual_Credit_Students_NonLow_Income: DataTypes.BIGINT,
    N_Students_who_took_Dual_Credit_classes_Grade_9_Total: DataTypes.BIGINT,
    N_Students_who_took_Dual_Credit_classes_Grade_10_Total: DataTypes.BIGINT,
    N_Students_who_took_Dual_Credit_classes_Grade_11_Total: DataTypes.BIGINT,
    N_Students_who_took_Dual_Credit_classes_Grade_12_Total: DataTypes.BIGINT,
    N_of_Students_who_passed_one_or_more_AP_exam_ALL_GRADES: DataTypes.BIGINT,
    AP_pass_rate: DataTypes.DECIMAL(0, 11),
    EBF_P_of_adequacy: DataTypes.DECIMAL(3,2),
    Administrator: DataTypes.STRING(500),
    Mailing_Address: DataTypes.STRING(500),
    City: DataTypes.STRING(500),
    Zip: DataTypes.STRING(500),
    Telephone: DataTypes.STRING(500),
    school_website: DataTypes.STRING(500),
    SAT_Reading_Total_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_White_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_White_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_White_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_White_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_White_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_White_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_White_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_White_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_B_or_AA_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_B_or_AA_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_B_or_AA_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_B_or_AA_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_B_or_AA_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_B_or_AA_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_B_or_AA_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_B_or_AA_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_H_or_L_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_H_or_L_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_H_or_L_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_H_or_L_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_H_or_L_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_H_or_L_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_H_or_L_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_H_or_L_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Asian_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Asian_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Asian_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Asian_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Asian_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Asian_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Asian_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Asian_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_NH_or_Other_PI_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_NH_or_Other_PI_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_NH_or_Other_PI_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_NH_or_Other_PI_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_NH_or_Other_PI_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_NH_or_Other_PI_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_NH_or_Other_PI_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_NH_or_Other_PI_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_AI_or_AN_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_AI_or_AN_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_AI_or_AN_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_AI_or_AN_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_AI_or_AN_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_AI_or_AN_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_AI_or_AN_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_AI_or_AN_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Two_or_More_Race_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Two_or_More_Race_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Two_or_More_Race_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Two_or_More_Race_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Two_or_More_Race_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Two_or_More_Race_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Two_or_More_Race_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Two_or_More_Race_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Low_Income_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Low_Income_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Low_Income_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Reading_Total_Low_Income_Students_Level_4_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Low_Income_Students_Level_1_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Low_Income_Students_Level_2_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Low_Income_Students_Level_3_P: DataTypes.DECIMAL(3,2),
    SAT_Math_Total_Low_Income_Students_Level_4_P: DataTypes.DECIMAL(3,2),
  }, {
    sequelize,
    modelName: "IL_DualCredit_Entity",
  });
  
  return IL_DualCredit_Entity;
};